version: '3.7'

services: 
  shoppinglist:
    build: 
      context: .
    volumes: 
      - static_data:/vol/web
      - /home/liset/dockerized_sl_app_NGINX_uWSGI/database:/db
    environment: 
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DEBUG=1
    
  proxy:
    build: 
      context: ./proxy
    volumes: 
      - static_data:/vol/static
    ports: 
      - "8080:8080"
    depends_on: 
      - shoppinglist

volumes: 
  static_data:
