version: '3.7'

services: 

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      POSTGRES_PASSWORD: postgres

docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres







  shoppinglist:
    build: .
    volumes: 
      - static_data:/vol/web
      - ./database:/db
    environment: 
      - STATIC_ROOT=/vol/web/static
      # - MEDIA_ROOT=/vol/web/media
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - DEBUG=1
      - DATABASE_TYPE=POSTGRESQL
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=sl_db
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on: 
      - db
    
  proxy:
    build: 
      context: ./proxy
    volumes: 
      - static_data:/vol/static
    ports: 
      - "8080:8080"
    depends_on: 
      - shoppinglist

volumes: 
  static_data:
  postgres_data:
